version: '3.9'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DJANGO_SECRET_KEY="django-insecure-1o&bc=do9i)utduf&zgp#=)*l7xtn3_$(ak47#)7=(^+ych^a*"
      - DJANGO_DEBUG=True
  db:
    image: postgres:13.9
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  postgres_data:

